resources:
  - ../../base
  - namespace.yaml

namespace: example-dev

patches:
   - target:
       kind: Route
       name: example
     patch: |-
       - op: replace
         path: /spec/host
         value: example-dev.localhost